name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.12.1
          run_install: false

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      - name: check formatting
        run: pnpm exec nx format:check

      - name: check nx sync
        run: pnpm exec nx sync:check

      - run: pnpm exec nx affected -t lint test build typecheck e2e-ci
